/* 
    OFFER is an example response from https://api.duffel.com/air/offers/
    PASSENGERS is an example of the passengers object required by the component, can be constructed from the OFFER object 
*/

const OFFER = {
  data: {
    updated_at: "2022-03-17T22:06:21.630667Z",
    total_emissions_kg: "662",
    total_currency: "GBP",
    total_amount: "655.50",
    tax_currency: "GBP",
    tax_amount: "99.99",
    slices: [
      {
        segments: [
          {
            passengers: [
              {
                passenger_id: "pas_0000AHW7inSU68yN5XnC4o",
                fare_basis_code: "Y20LGTN2",
                cabin_class_marketing_name: "Economy",
                cabin_class: "economy",
                baggages: [
                  {
                    type: "checked",
                    quantity: 1,
                  },
                ],
              },
              {
                passenger_id: "pas_0000AHW7inSU68yN5XnC4p",
                fare_basis_code: "Y20LGTN2",
                cabin_class_marketing_name: "Economy",
                cabin_class: "economy",
                baggages: [
                  {
                    type: "checked",
                    quantity: 1,
                  },
                ],
              },
            ],
            origin_terminal: "2",
            origin: {
              type: "airport",
              time_zone: "Europe/London",
              name: "Heathrow Airport",
              longitude: -0.458118,
              latitude: 51.470311,
              id: "arp_lhr_gb",
              icao_code: "EGLL",
              iata_country_code: "GB",
              iata_code: "LHR",
              iata_city_code: "LON",
              city_name: "London",
              city: {
                type: "city",
                time_zone: null,
                name: "London",
                longitude: null,
                latitude: null,
                id: "cit_lon_gb",
                icao_code: null,
                iata_country_code: "GB",
                iata_code: "LON",
                iata_city_code: "LON",
                city_name: null,
              },
              airports: null,
            },
            operating_carrier_flight_number: "5990",
            operating_carrier: {
              name: "Duffel Airways",
              id: "arl_00009VME7D6ivUu8dn35WK",
              iata_code: "ZZ",
            },
            marketing_carrier_flight_number: "5990",
            marketing_carrier: {
              name: "Duffel Airways",
              id: "arl_00009VME7D6ivUu8dn35WK",
              iata_code: "ZZ",
            },
            id: "seg_0000AHW7indpPy2xej6Fl6",
            duration: "PT8H8M",
            distance: "5666.39351516012",
            destination_terminal: "1",
            destination: {
              type: "airport",
              time_zone: "America/New_York",
              name: "John F. Kennedy International Airport",
              longitude: -73.778519,
              latitude: 40.640556,
              id: "arp_jfk_us",
              icao_code: "KJFK",
              iata_country_code: "US",
              iata_code: "JFK",
              iata_city_code: "NYC",
              city_name: "New York",
              city: {
                type: "city",
                time_zone: null,
                name: "New York",
                longitude: null,
                latitude: null,
                id: "cit_nyc_us",
                icao_code: null,
                iata_country_code: "US",
                iata_code: "NYC",
                iata_city_code: "NYC",
                city_name: null,
              },
              airports: null,
            },
            departing_at: "2022-06-01T23:00:00",
            arriving_at: "2022-06-02T07:08:00",
            aircraft: {
              name: "Boeing 777-300",
              id: "arc_00009VMF8AhXSSRnQDI6HE",
              iata_code: "773",
            },
          },
        ],
        origin_type: "airport",
        origin: {
          type: "airport",
          time_zone: "Europe/London",
          name: "Heathrow Airport",
          longitude: -0.458118,
          latitude: 51.470311,
          id: "arp_lhr_gb",
          icao_code: "EGLL",
          iata_country_code: "GB",
          iata_code: "LHR",
          iata_city_code: "LON",
          city_name: "London",
          city: {
            type: "city",
            time_zone: null,
            name: "London",
            longitude: null,
            latitude: null,
            id: "cit_lon_gb",
            icao_code: null,
            iata_country_code: "GB",
            iata_code: "LON",
            iata_city_code: "LON",
            city_name: null,
          },
          airports: null,
        },
        id: "sli_0000AHW7ineBOeKXfpGXJL",
        fare_brand_name: "Basic",
        duration: "PT8H8M",
        destination_type: "airport",
        destination: {
          type: "airport",
          time_zone: "America/New_York",
          name: "John F. Kennedy International Airport",
          longitude: -73.778519,
          latitude: 40.640556,
          id: "arp_jfk_us",
          icao_code: "KJFK",
          iata_country_code: "US",
          iata_code: "JFK",
          iata_city_code: "NYC",
          city_name: "New York",
          city: {
            type: "city",
            time_zone: null,
            name: "New York",
            longitude: null,
            latitude: null,
            id: "cit_nyc_us",
            icao_code: null,
            iata_country_code: "US",
            iata_code: "NYC",
            iata_city_code: "NYC",
            city_name: null,
          },
          airports: null,
        },
        conditions: {
          change_before_departure: {
            penalty_currency: null,
            penalty_amount: null,
            allowed: false,
          },
        },
      },
    ],
    payment_requirements: {
      requires_instant_payment: false,
      price_guarantee_expires_at: "2022-03-19T22:05:47Z",
      payment_required_by: "2022-03-20T22:05:47Z",
    },
    passengers: [
      {
        type: "adult",
        loyalty_programme_accounts: [],
        id: "pas_0000AHW7inSU68yN5XnC4o",
        given_name: null,
        family_name: null,
        age: null,
      },
      {
        type: "adult",
        loyalty_programme_accounts: [],
        id: "pas_0000AHW7inSU68yN5XnC4p",
        given_name: null,
        family_name: null,
        age: null,
      },
    ],
    passenger_identity_documents_required: false,
    owner: {
      name: "Duffel Airways",
      id: "arl_00009VME7D6ivUu8dn35WK",
      iata_code: "ZZ",
    },
    live_mode: false,
    id: "off_0000AHW7ineBOeKXfpGXJM",
    expires_at: "2022-03-17T22:35:47.341823Z",
    created_at: "2022-03-17T22:05:47.348961Z",
    conditions: {
      refund_before_departure: {
        penalty_currency: "GBP",
        penalty_amount: "110.00",
        allowed: true,
      },
      change_before_departure: {
        penalty_currency: null,
        penalty_amount: null,
        allowed: false,
      },
    },
    base_currency: "GBP",
    base_amount: "555.51",
    available_services: [
      {
        type: "baggage",
        total_currency: "GBP",
        total_amount: "20.00",
        segment_ids: ["seg_0000AHW7indpPy2xej6Fl6"],
        passenger_ids: ["pas_0000AHW7inSU68yN5XnC4o"],
        metadata: {
          type: "checked",
          maximum_weight_kg: 23,
          maximum_length_cm: null,
          maximum_height_cm: null,
          maximum_depth_cm: null,
        },
        maximum_quantity: 1,
        id: "ase_0000AHW7lxmj1x46DSYe7W",
      },
      {
        type: "baggage",
        total_currency: "GBP",
        total_amount: "20.00",
        segment_ids: ["seg_0000AHW7indpPy2xej6Fl6"],
        passenger_ids: ["pas_0000AHW7inSU68yN5XnC4p"],
        metadata: {
          type: "checked",
          maximum_weight_kg: 23,
          maximum_length_cm: null,
          maximum_height_cm: null,
          maximum_depth_cm: null,
        },
        maximum_quantity: 1,
        id: "ase_0000AHW7lxmj1x46DSYe7X",
      },
    ],
    allowed_passenger_identity_document_types: [],
  },
};

const PASSENGERS = [
  {
    id: "pas_0000AHW7inSU68yN5XnC4o",
    name: "Tony Stark",
  },
  {
    id: "pas_0000AHW7inSU68yN5XnC4p",
    name: "Bruce Banner",
  },
];

const DATA = {
  OFFER,
  PASSENGERS,
};

export default DATA;
